---
#
# Ansible managed
#
repository:
  description: Install and configure aide on your system.
  homepage: https://robertdebock.nl/
  topics: aide, ids, monitoring, system, security, ansible, molecule, tox, playbook
